imagePullSecrets:
  - name: regcred

imagePullPolicy: IfNotPresent

simulation:
  OE_SIMULATION: "1"

resourceInjection: "disabled"

dcap: {}

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.6.0

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.6.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.6.0
