imagePullSecrets:
  - name: regcred

imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m

simulation:
  OE_SIMULATION: "0"

resourceInjection: "enabled"

dcap:
  qpl: "azure"
  pccsUrl: "https://localhost:8081/sgx/certification/v3/"
  useSecureCert: "TRUE"

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.6.0

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.6.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.6.0
