# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import marble_pb2 as marble__pb2


class OperationTrackerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartOperation = channel.unary_unary(
                '/rpc.OperationTracker/StartOperation',
                request_serializer=marble__pb2.StartOperationReq.SerializeToString,
                response_deserializer=marble__pb2.StartOperationResp.FromString,
                )


class OperationTrackerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationTrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOperation,
                    request_deserializer=marble__pb2.StartOperationReq.FromString,
                    response_serializer=marble__pb2.StartOperationResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.OperationTracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OperationTracker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.OperationTracker/StartOperation',
            marble__pb2.StartOperationReq.SerializeToString,
            marble__pb2.StartOperationResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
