apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
      version: v1
  template:
    metadata:
      labels:
        app: vote-bot
        version: v1
    spec:
      containers:
      - command:
        - /emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc:443
        image: {{ .Values.web.image }}:{{ .Values.web.imageVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: vote-bot
        resources:
          requests:
            cpu: 10m
      imagePullSecrets:
      - name: regcred
