kind: ServiceAccount
apiVersion: v1
metadata:
  name: web
  namespace: emojivoto
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v1
spec:
  serviceName: "web"
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v1
  template:
    metadata:
      labels:
        app: web-svc
        version: v1
        marblerun/marbletype: web
        marblerun/resource-injection: {{ .Values.resourceInjection }}
    spec:
      serviceAccountName: web
      containers:
      - env:
        - name: OE_SIMULATION
          valueFrom:
            configMapKeyRef:
              name: oe-config
              key: OE_SIMULATION
        {{ if .Values.dcap  }}
        - name: DCAP_LIBRARY
          value: "{{ .Values.dcap.qpl }}"
        {{ end }}
        image: {{ .Values.web.image }}:{{ .Values.web.imageVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: web-svc
        ports:
        - containerPort: 4433
          name: https
        - containerPort: 8080
          name: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: web-data
          mountPath: /web-svc/data
        {{ if .Values.dcap }}
        - name: dcap-conf
          mountPath: /etc/sgx_default_qcnl.conf
          subPath: sgx_default_qcnl.conf
        {{ end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{ if .Values.dcap }}
      - name: dcap-conf
        configMap:
          name: emojivoto-dcap-config
      {{ end }}
  volumeClaimTemplates:
  - metadata:
      name: web-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto
spec:
  type: NodePort
  selector:
    app: web-svc
  ports:
  - name: https
    port: 443
    targetPort: 4433
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc-http
  namespace: emojivoto
spec:
  type: ClusterIP
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 8080
